name: Build for iOS

on:
  workflow_call:
    inputs:
      tag:
        description: "tag"
        required: false
        default: ""
        type: string
  workflow_dispatch:

jobs:
  build-macos-app:
    name: Release IOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable


      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign --dart-define-from-file=pili_release.json
          ln -sf ./build/ios/iphoneos Payload
          zip -r9 BiliPlus_ios_${{env.version}}.ipa Payload/runner.app

      - name: Release
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.tag }}
          files: |
            BiliPlus_ios_*.ipa

      - name: Upload ios release
        uses: actions/upload-artifact@v4
        with:
          name: iOS-release
          path: BiliPlus_ios_*.ipa
